### PR TITLE
feature(test): setup running tests with cmake and IDE

### PR DESCRIPTION
**Pull request by CodeLieutenant**

### CODE REVIEW

**Comment by danielhe4rt** [comment]
you can make it, keep going buddy

**Comment by danielhe4rt** [comment]
Almost there!!!!

**Comment by CodeLieutenant** [comment]
> Almost there!!!!

DONEEE!!!

**Comment by CodeLieutenant** [comment]
> > Almost there!!!!
> 
> DONEEE!!!

Now needs to go back to failing, cause, this is just to get the cache up and running, and tests are not running...

**Comment by CodeLieutenant** [comment]
@DanielHe4rt Wanna try to fix the tests??

**Pull request merged**
